version: 2
updates:
- package-ecosystem: devcontainers
  directory: /
  schedule:
    interval: weekly
    day: friday
  target-branch: main
  reviewers:
  - gsuquet
  assignees:
  - gsuquet
  commit-message:
    prefix: ':technologist: chore(dev):'

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: friday
  reviewers:
  - gsuquet
  assignees:
  - gsuquet
  commit-message:
    prefix: ':green_heart: chore(ci):'
