name: CI
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    uses: gsuquet/workflows/.github/workflows/automation-labeler.yml@c694c4aa3f2ab4962975b33ad1673c900537714b

  update-package-list:
    permissions:
      contents: write
    uses: gsuquet/workflows/.github/workflows/integration-modification-script.yml@c694c4aa3f2ab4962975b33ad1673c900537714b
    with:
      script_path: ./scripts/generate_package_list.sh
      ref: ${{ github.head_ref }}
      commit_message: ':memo: doc: Update package list in README.md'
