name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    uses: gsuquet/workflows/.github/workflows/automation-labeler.yml@main
