name: CI
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    uses: gsuquet/workflows/.github/workflows/automation-labeler.yml@7e887cf4d10f445ae67ba60549cc1e3c59c8adc9

  update-package-list:
    permissions:
      contents: write
    uses: gsuquet/workflows/.github/workflows/integration-modification-script.yml@7e887cf4d10f445ae67ba60549cc1e3c59c8adc9
    with:
      script_path: ./scripts/generate_package_list.sh
      ref: ${{ github.head_ref }}
      commit_message: ':memo: doc: Update package list in README.md'
