name: Security
on:
  branch_protection_rule:
  push:
    branches:
      - main

permissions: {}

jobs:
  ossf-scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: gsuquet/workflows/.github/workflows/security-ossf-scorecard.yml@aebb532da1ae58102592b7fc24c073be101326e6
    with:
      harden_runner: true
    secrets:
      scorecard_token: ${{ secrets.SCORECARD_TOKEN }}
