name: Security
on:
  branch_protection_rule:
  push:
    branches:
      - main

permissions: {}

jobs:
  ossf-scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: gsuquet/workflows/.github/workflows/security-ossf-scorecard.yml@0f7c5d8c6bdbc14386b308fb381b0611934f8482 # v1.2.5
    with:
      harden_runner: true
    secrets:
      scorecard_token: ${{ secrets.SCORECARD_TOKEN }}
