name: Security
on:
  branch_protection_rule:
  push:
    branches:
      - main

permissions: {}

jobs:
  ossf-scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: gsuquet/workflows/.github/workflows/security-ossf-scorecard.yml@43c68523c48e8f1b57e7ef87303e26abcf1e6e1b # v1.2.6
    with:
      harden_runner: true
    secrets:
      scorecard_token: ${{ secrets.SCORECARD_TOKEN }}
